[package]
name = "mumps-problem-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
russell_lab = { version = "0.4.1" }
russell_sparse = { version = "0.3.1" }