[package]
name = "mumps-problem-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
russell_lab = { path = "../russell/russell_lab" }
russell_sparse = { path = "../russell/russell_sparse" }